train:
    num_labels: 2
    lr: 2e-5
    patience: 10
    dataset_path: "data/train_2000_same_question_parsed.csv"
    train_data_ratio: 0.8
    devices: 2
    max_epochs: 100
    early_stopping_patience: 10
